[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "langgraph>=0.2.33",
    "langchain-core>=0.3.0", 
    "langchain-openai>=0.2.0",
    "jupyter==1.1.1",
    "notebook==7.4.5",
    "ipython<9"
]
